### PR TITLE
set permissions for entrypoint

### PR DESCRIPTION
**Pull request by albjeremias**

### CODE REVIEW

**Comment by HarelM** [comment]
Are you sure this is needed? I can run the image without this...

**Comment by albjeremias** [comment]
> Are you sure this is needed? I can run the image without this...

do it on a blank server.. or a blank username.. ;)

**Comment by HarelM** [comment]
@zstadler can you take a look at this? when pulling the latest image this issue seems to manifest.
@albjeremias you can use 6.2 image for now, which doesn't have this issue.
I'm sure there's a better way to do it without adding chmod to the dockerfile as I already removed it in the past and it was working, see here: 8c0bf15c6d6dee72653a888d3b3f69fc7c1e9c2a

**Comment by zstadler** [comment]
The missing permissions need to be set in the repository rather than as an action in `Dockerfile`.

I've submitted PR #31 as a replacement for this PR.

**Comment by HarelM** [comment]
Closing this for now, if that didn't help we can always reopen this one.

**Pull request closed without merging**
